name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    
    steps:
    - uses: actions/checkout@v2
    
    # Login Docker
    - name: Login Docker Account
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    # Build docker image
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag diepmyduong/it-house-shop:github
      
    # Push Docker image
    - name: Push Docker image
      run: |
        docker push diepmyduong/it-house-shop:github
